cloud:
  aws:
    credentials:
      access-key: AKIAUCLV4BWNWOG6Z3PQ
      secret-key: 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
    region:
      static: eu-west-2
    stack:
      auto: false

application:
  bucket:
    name: booking-system-storage

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 50MB
      max-request-size: 100MB